// Empirical capability probe for the target GPU. Emits Makefile variables on
// stdout (cached as common/caps.mk); human detail goes to stderr.
//
// The cluster question cannot be resolved from documentation for sm_121:
// sources conflict on whether consumer Blackwell supports >1-block clusters.
// So: query the attribute, query the occupancy API, then launch a real
// 2-block cluster and have the kernel report cluster_group::num_blocks().
// Only if the hardware genuinely groups the blocks do we attempt
// cluster.sync(), and even then behind a host-side deadlock timeout.

#include <chrono>
#include <cooperative_groups.h>
#include <cstdio>
#include <cuda_runtime.h>
#include <unistd.h>

#include "puzzle_utils.cuh"

namespace cg = cooperative_groups;

__global__ void ClusterProbe(int* out) {
  cg::cluster_group c = cg::this_cluster();
  if (threadIdx.x == 0) {
    out[blockIdx.x * 2] = (int)c.num_blocks();
    out[blockIdx.x * 2 + 1] = (int)c.block_rank();
  }
}

__global__ void ClusterSyncProbe(int* out) {
  cg::cluster_group c = cg::this_cluster();
  c.sync();
  if (threadIdx.x == 0) out[c.block_rank()] = (int)c.num_blocks();
}

int main() {
  cudaDeviceProp p;
  CHECK_CUDA(cudaGetDeviceProperties(&p, 0));
  fprintf(stderr, "device: %s sm_%d%d, %d SMs, %zu KiB smem/block (%zu optin)\n",
          p.name, p.major, p.minor, p.multiProcessorCount,
          p.sharedMemPerBlock / 1024, p.sharedMemPerBlockOptin / 1024);

  printf("# generated by scripts/probe_caps.cu -- do not edit, do not commit\n");
  printf("CAPS_ARCH := sm_%d%d\n", p.major, p.minor);

  int attr = 0;
  CHECK_CUDA(cudaDeviceGetAttribute(&attr, cudaDevAttrClusterLaunch, 0));
  printf("CAPS_CLUSTER_LAUNCH := %d\n", attr);
  if (!attr) {
    fprintf(stderr, "cudaDevAttrClusterLaunch = 0: no cluster support at all\n");
    printf("CAPS_CLUSTER_MAX := 0\nCAPS_CLUSTER_REAL := 0\nCAPS_CLUSTER_SYNC := 0\n");
    return 0;
  }

  cudaLaunchConfig_t cfg = {};
  cfg.gridDim = dim3(2, 1, 1);
  cfg.blockDim = dim3(32, 1, 1);
  int maxc = 0;
  cudaError_t e = cudaOccupancyMaxPotentialClusterSize(&maxc, ClusterProbe, &cfg);
  if (e != cudaSuccess) {
    fprintf(stderr, "cudaOccupancyMaxPotentialClusterSize: %s\n",
            cudaGetErrorString(e));
    (void)cudaGetLastError();  // clear sticky error; 0 already records the refusal
    maxc = 0;
  }
  printf("CAPS_CLUSTER_MAX := %d\n", maxc);

  int real = 0, sync_ok = 0;
  int* d = nullptr;
  CHECK_CUDA(cudaMalloc(&d, 4 * sizeof(int)));
  CHECK_CUDA(cudaMemset(d, 0xff, 4 * sizeof(int)));

  cudaLaunchAttribute a[1];
  a[0].id = cudaLaunchAttributeClusterDimension;
  a[0].val.clusterDim.x = 2;
  a[0].val.clusterDim.y = 1;
  a[0].val.clusterDim.z = 1;
  cfg.attrs = a;
  cfg.numAttrs = 1;

  e = cudaLaunchKernelEx(&cfg, ClusterProbe, d);
  if (e != cudaSuccess) {
    fprintf(stderr, "2-block cluster launch refused: %s\n", cudaGetErrorString(e));
    (void)cudaGetLastError();  // clear sticky error; refusal is the probe result
  } else {
    CHECK_CUDA(cudaDeviceSynchronize());
    int h[4];
    CHECK_CUDA(cudaMemcpy(h, d, sizeof h, cudaMemcpyDeviceToHost));
    fprintf(stderr,
            "cluster launch accepted: block0 {num_blocks=%d rank=%d} "
            "block1 {num_blocks=%d rank=%d}\n", h[0], h[1], h[2], h[3]);
    real = (h[0] == h[2]) ? h[0] : 0;
    if (real == 2 && ((h[1] == 0 && h[3] == 1) || (h[1] == 1 && h[3] == 0))) {
      CHECK_CUDA(cudaMemset(d, 0, 4 * sizeof(int)));
      cudaEvent_t done;
      CHECK_CUDA(cudaEventCreate(&done));
      e = cudaLaunchKernelEx(&cfg, ClusterSyncProbe, d);
      if (e != cudaSuccess) {
        fprintf(stderr, "sync probe launch refused: %s\n", cudaGetErrorString(e));
        (void)cudaGetLastError();  // clear sticky error; sync_ok stays 0
      } else {
        CHECK_CUDA(cudaEventRecord(done));
        auto t0 = std::chrono::steady_clock::now();
        for (;;) {
          cudaError_t q = cudaEventQuery(done);
          if (q == cudaSuccess) {
            int h2[2];
            CHECK_CUDA(cudaMemcpy(h2, d, sizeof h2, cudaMemcpyDeviceToHost));
            sync_ok = (h2[0] == 2 && h2[1] == 2) ? 1 : 0;
            fprintf(stderr, "cluster.sync() completed: ranks saw num_blocks "
                    "{%d, %d}\n", h2[0], h2[1]);
            break;
          }
          if (q != cudaErrorNotReady) {
            fprintf(stderr, "sync probe failed: %s\n", cudaGetErrorString(q));
            (void)cudaGetLastError();  // clear sticky error; sync_ok stays 0
            break;
          }
          if (std::chrono::steady_clock::now() - t0 > std::chrono::seconds(10)) {
            fprintf(stderr,
                    "cluster.sync() DEADLOCK: 10s without completion. "
                    "Hard-exiting; driver will tear down the stuck kernel.\n");
            printf("CAPS_CLUSTER_REAL := %d\nCAPS_CLUSTER_SYNC := 0\n", real);
            fflush(stdout);
            _exit(0);  // caps.mk must still record the finding
          }
          usleep(10000);
        }
      }
    } else if (real != 2) {
      fprintf(stderr, "silent downgrade: hardware reports cluster size %d\n",
              real);
    }
  }

  printf("CAPS_CLUSTER_REAL := %d\nCAPS_CLUSTER_SYNC := %d\n", real, sync_ok);
  CHECK_CUDA(cudaFree(d));
  return 0;
}
